services:
  backend:
    build:
      context: ./finanzasparahippies-backend
      dockerfile: Dockerfile
    container_name: fph_backend
    restart: always
    env_file:
      - ./finanzasparahippies-backend/.env
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
    volumes:
      - ./finanzasparahippies-backend:/app:z
    expose:
      - 8000
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    networks:
       - prod_network

  fph_frontend:
    build:
      context: ./finanzasparahippies-front
      dockerfile: Dockerfile
    container_name: fph_frontend
#    volumes:
#      - ./finanzasparahippies-front:/app:z
#      - /app/node_modules
#      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=https://localhost/api
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    ports:
      - "3001:3000"
    restart: always
    networks:
       - prod_network

  nginx:
    image: nginx:1.25-alpine
    container_name: fph_nginx
    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
    environment:
      - FPH_SSL_CERT_PATH=/etc/letsencrypt/live/finanzasparahippies.com-0001/fullchain.pem
      - FPH_SSL_KEY_PATH=/etc/letsencrypt/live/finanzasparahippies.com-0001/privkey.pem
      - NECTAR_SSL_CERT_PATH=${NECTAR_SSL_CERT_PATH:-/etc/nectar-ssl/live/nectarlabs.dev/fullchain.pem}
      - NECTAR_SSL_KEY_PATH=${NECTAR_SSL_KEY_PATH:-/etc/nectar-ssl/live/nectarlabs.dev/privkey.pem}
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro,z
      - ./finanzasparahippies-backend/static:/app/static:ro,z
      - ./finanzasparahippies-backend/media:/app/media:ro,z
      - ./nectar-ssl:/etc/nectar-ssl:ro,z
      - /etc/letsencrypt:/etc/letsencrypt:ro,z
    depends_on:
      - backend
      - fph_frontend
    networks:
      - default
      - prod_network

networks:
  default:
    driver: bridge
  prod_network:
    external: true

volumes:
  nectarlabs_certbot-conf:
    external: true
