services:

  fph-backend-staging:
    build:
      context: ./finanzasparahippies-backend
      dockerfile: Dockerfile
    container_name: fph_backend_staging
    restart: always
    env_file:
      - .env.staging
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
    volumes:
      - ./finanzasparahippies-backend:/app:z
    networks:
      - prod_network

  frontend-staging:
    build:
      context: ./finanzasparahippies-front
      dockerfile: Dockerfile
    container_name: fph_frontend_staging
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NODE_ENV=development
    restart: always
    networks:
      - prod_network

volumes:
  postgres_data_staging:

networks:
  prod_network:
    external: true
    name: prod_network
