# Generated by Django 6.0 on 2026-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('COACH', 'Coach'), ('GUEST', 'Guest')], default='STUDENT', max_length=20),
        ),
    ]
